server:
  error:
    include-stacktrace:never

spring:
    
  datasource:
      url: jdbc:mysql://10.0.0.127:3306/testes?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      username: root
      password: 123456

jpa:
  hibernate:
      ddl-auto: update
