version: '3.8'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.18.0
  

    ports:
      - "9200:9200"
      - "9300:9300"

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      

