# jwt.private.key = classpath: app.key
jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:pub.key


server:
  error:
    include-stacktrace : never

spring:
    
  datasource:
      url: jdbc:mysql://10.0.0.127:3306/spring_security_teste?allowPublicKeyRetrieval=true
      username: root
      password: 123456

  jpa:
    hibernate:
        ddl-auto: update

    # isso é para mostrar o sql gerado no console
    show-sql: true